Algoritmo "67"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/3/2022
Var
// Seção de Declarações das variáveis 
   n,c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um numero para ver sua contagem ate ele: ")
   leia(n)
   para c <- 0 ate (n-2) faca
      escreva(c,", ")
   fimpara
   escreva(n-1," e ",n," Fim!")
Fimalgoritmo