Algoritmo "71"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/3/2022
Var
// Seção de Declarações das variáveis 
   vet: vetor[0..7]de inteiro
   i: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para i <- 0 ate 7 faca
      vet[i] <- 999
      escreva(vet[i])
   fimpara

Fimalgoritmo