Algoritmo "72"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/3/2022
Var
// Seção de Declarações das variáveis 
   vet: vetor[1..10]de real
   i: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para i <- 1 ate 10 faca
      vet[i] <- 5 * i
      escreva(vet[i])
   fimpara

Fimalgoritmo