algoritmo "CadeiraCinema"
var
   cadeira: vetor[1..10]de caractere
   c: inteiro
   resp: caractere
inicio
   para c <- 1 ate 10 faca

   fimpara
   escreval()
   escreval("------------------------------------------------------------------------")
   repita
      escreva("Reservar a cadeira: ")
      leia(cadeira[c])
   
   
   
   
   
   
   
   
   escreva("Deseja reservar outra cadeira? ")
   leia(resp)
   ate(resp = "n")
fimalgoritmo